language: go
go:
 - 1.14
before_install:
  - sudo apt-get -y install tree
addons:
  apt:
    update: true
before_deploy:
  - mkdir release
  - awk '$0 ~ /## \[.+\]/ {release = $2} release == "[]" {print $0}' CHANGELOG.md > release/CHANGELOG
deploy:
  provider: releases
  edge: true
  api_key: "$GITHUB_OAUTH_TOKEN"
  release_notes_file: release/CHANGELOG
  file: "build/**/*"
  skip_cleanup: true
  on:
    tags: true