version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make test

  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make build SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
      - persist_to_workspace:
          root: .
          paths:
            - build

  docker_release:
    docker:
      - image: circleci/golang:1.14
    environment:
      DOCKERHUB_USERNAME=sklikdevops
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: ln -s build/linux-amd64/slo-exporter ./slo-exporter
      - run: make docker-docker SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
      - run: echo "${DOCKERHUB_PASSWORD}" | docker login -u="${DOCKERHUB_USERNAME}" --password-stdin
      - run: make docker-push

workflows:
  version: 2
  slo-exporter:
    jobs:
      - lint
      - test
      - build
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
      #- github_release
