version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make lint

  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make test

  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: make build SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
      - persist_to_workspace:
          root: .
          paths:
            - build

  docker_release:
    docker:
      - image: circleci/golang:1.14
    environment:
      DOCKERHUB_USERNAME=sklikdevops
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run:
          command: |
            cp build/linux-amd64/slo_exporter ./slo_exporter
            echo "${DOCKERHUB_PASSWORD}" | docker login -u="${DOCKERHUB_USERNAME}" --password-stdin
            export SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
            make docker-build
            make docker-push

  github_release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            export SLO_EXPORTER_VERSION=${CIRCLE_TAG:-$CIRCLE_SHA1}
            go get github.com/github-release/github-release
            make github-release

workflows:
  version: 2
  slo-exporter:
    jobs:
      - lint
      - test
      - build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
      - github_release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/

# check job for correct changelog in case of tagged pipeline